### ISSUE TITLE
Bug: `cmd+shift+g` not working as it stays in normal mode

### ISSUE THREAD

**Issue by jdrupal-dev** [chrisgrieser/finder-vim-mode#7]
### Feature Requested

This plugin removes the default / keymap which works as a file search in finder.
What are the options to get that back, while keeping all of the other keymaps from this plugin?

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have read about the limitations of Karabiner plugins in the [Caveats section of the README](..#caveats).

**Comment by chrisgrieser** [comment]
> the default / keymap which works as a file search in finder

How does that work? I tried `/` with the US as well as the German keyboard layout, both with Karabiner disabled, and nothing happens in Finder.

Also, I just checked, `/` is not overridden by this plugin?

**Comment by jdrupal-dev** [comment]
Hmm, for some reason / used to open Go To (Shift + Cmd + G), but it doesn't do that anymore.
I also noticed that Go To doesn't work when vim mode is enabled, because enter selects the current item, so there's no way to enter insert mode.

**Comment by chrisgrieser** [comment]
> Hmm, for some reason / used to open Go To (Shift + Cmd + G), but it doesn't do that anymore.

ah yes, that was actually a feature of an older version of this plugin, not a Finder functionality. You probably have used an older version of finder vim mode and updated recently, I assume?

> I also noticed that Go To doesn't work when vim mode is enabled, because enter selects the current item, so there's no way to enter insert mode.

Ah that a bug. I never thought that people actually use that goto feature, since it's so hidden as well as very lacking in my view. Nevertheless, I pushed a fix, so that you can use it, if you want nonetheless want to.

**Comment by jdrupal-dev** [comment]
Wow, that was fast! Thank you, it works now :)
